### ISSUE TITLE
ExoQuant causes overflow error on 3rd line of MakeHash function

### ISSUE THREAD

**Issue by ljf118** [DavidSM64/ExoQuantVB#1]
Here is the issue as best as I can describe it. When hashing each pixel which is stored in a byte() stream there is an overflow on any color passed to it on the third line of the subroutine:
The real problem is I seem to be challenged trying to understand bit shifting. This error also occurs in the c# version.

Private Function MakeHash(ByVal rgba As Uinteger) As UInteger
            Try
                '1
                rgba -= (rgba >> 13) Or (rgba << 19)
                '2
                rgba -= (rgba >> 13) Or (rgba << 19)
                '3
                **rgba -= (rgba >> 13) Or (rgba << 19)**

                rgba -= (rgba >> 13) Or (rgba << 19)
                rgba -= (rgba >> 13) Or (rgba << 19)
                rgba = rgba And (EXQ_HASH_SIZE - 1)
                Return rgba
            Catch ex As Exception
                MessageBox.Show("ExoQuant.MakeHash: " + ex.Message + " " + ex.StackTrace)
                Return 255
            End Try
        End Function

The function is called from:

               

Public Sub Feed(ByVal pData As Byte())
            Dim channelMask As Byte = &HFF00 >> pExq.numBitsPerChannel
            Dim nPixels As Integer = Int(pData.Length / 4)
            For i As Integer = 0 To nPixels - 1
                Dim r As Byte = pData(i * 4 + 0),
                    g As Byte = pData(i * 4 + 1),
                    b As Byte = pData(i * 4 + 2),
                    a As Byte = pData(i * 4 + 3)
                'If pdata(i * 4 + 3) = 0 Then
                '    a = 255
                'Else
                '    a = pData(i * 4 + 3)
                'End If
                Dim hash As UInteger = MakeHash(ToRGBA(r, g, b, a))
                Dim pCur As ExqHistogramEntry = pExq.pHash(hash)

                While pCur IsNot Nothing AndAlso (pCur.ored <> r OrElse pCur.ogreen <> g OrElse pCur.oblue <> b OrElse pCur.oalpha <> a)
                    pCur = pCur.pNextInHash
                End While

                If pCur IsNot Nothing Then
                    pCur.num += 1
                Else
                    pCur = New ExqHistogramEntry()
                    pCur.pNextInHash = pExq.pHash(hash)
                    pExq.pHash(hash) = pCur
                    pCur.ored = r
                    pCur.ogreen = g
                    pCur.oblue = b
                    pCur.oalpha = a
                    r = r And channelMask
                    g = g And channelMask
                    b = b And channelMask
                    pCur.color.r = r / 255.0F * SCALE_R
                    pCur.color.g = g / 255.0F * SCALE_G
                    pCur.color.b = b / 255.0F * SCALE_B
                    pCur.color.a = a / 255.0F * SCALE_A

                    If pExq.transparency Then
                        pCur.color.r *= pCur.color.a
                        pCur.color.g *= pCur.color.a
                        pCur.color.b *= pCur.color.a
                    End If

                    pCur.num = 1
                    pCur.palIndex = -1
                    pCur.ditherScale.r = -1
                    pCur.ditherScale.g = -1
                    pCur.ditherScale.b = -1
                    pCur.ditherScale.a = -1
                    pCur.ditherIndex(0) = -1
                    pCur.ditherIndex(1) = -1
                    pCur.ditherIndex(2) = -1
                    pCur.ditherIndex(3) = -1
                End If
            Next
        End Sub

The ToRGBA function is:
Hide   Copy Code
Private Function ToRGBA(ByVal r As UInteger, ByVal g As UInteger, ByVal b As UInteger, ByVal a As UInteger) As UInteger
         Return r Or (g << 8) Or (b << 16) Or (a << 24)
     End Function

This is the image I'm having the hardest time with. When reducing colors most algorithms lose the yellow in the eyes.
![catwyelloweyes](https://user-images.githubusercontent.com/16807764/71772100-4b27b900-2f13-11ea-88ee-f8867064e160.jpg)

**Comment by DavidSM64** [comment]
Hey, sorry for being late with this response.

You are passing in an array with 4 bytes per pixel RGBA values right? It does not work with 3 bytes per pixel RGB arrays. Can you provide some images that produce the overflow error? The image you provided doesn't have any issues from what I can tell.

As for the eyes, I'm guessing the yellow gets removed since there are very few yellow pixels to begin with. The algorithm only has up to 256 colors to work with, so it needs more shades of gray and orange to maintain better detail. I think the image looks close-enough in my opinion.

![alt text](https://i.imgur.com/mmks67F.png)

**Comment by ljf118** [comment]
Thanks for getting back to me. That cat is a killer because I'm limited to < 48 colors. It's why I keep looking for different methods. Could my issue be converting 24 bit images to 32 bits? So the alpha is 0?

Also I just ran that same cat again and same issue. Can I send you my VB code and a few images? So you can see the issue?

I spent a lot of time trying to understand but shifting. I think I got it but still trying to grasp the implications. I'm a real back as in not very good at coding but always get it done somehow.

Should I post the code or send it direct?

Again I really appreciate the response.

Larry.


On January 18, 2020, at 9:16 PM, DavidSM64 <notifications@github.com> wrote:


Hey, sorry for being late with this response.

You are passing in an array with 32-bit RGBA values right? It does not work with 24-bit RGB arrays. Can you provide some images that produce the overflow error? The image you provided doesn't have any issues from what I can tell.

As for the eyes, I'm guessing the yellow gets removed since there are very few yellow pixels to begin with. The algorithm only has up to 256 colors to work with, so it needs more shades of gray and orange to maintain better detail. I think the image looks close-enough in my opinion.

[alt text]<https://camo.githubusercontent.com/5c153a59d273add07e1b784294a44bd7601e6f25/68747470733a2f2f692e696d6775722e636f6d2f6d6d6b733637462e706e67>

**Comment by DavidSM64** [comment]
Oh! You mentioned that you had the same issue with the C# version, so I used that version since I prefer that language to Visual Basic. I tested your image with the C# version and it worked fine. I just ported my test code to visual basic and now I'm getting that overflow error. After looking around online, I think I know what the issue is.

It turns out that Visual Basic checks for overflows on integers, whereas C# does not: https://stackoverflow.com/questions/4515102/unsigned-left-shift-in-vb-net

As a temporary fix, you can remove integer overflow checks in the project properties. Make sure that the "Remove integer overflow checks" is enabled for all configurations and rebuild your solution. Let me know if this works for you or not.

![alt text](https://i.imgur.com/Tonru9y.png)

**Comment by ljf118** [comment]
Your a  gentleman and a scholar. I'll give it a try.

Larry


On January 19, 2020, at 12:50 PM, DavidSM64 <notifications@github.com> wrote:


Oh! You mentioned that you had the same issue with the C# version, so I used that version since I prefer that language to Visual Basic. I tested your image with the C# version and it worked fine. I just ported my test code to visual basic and now I'm getting that overflow error. After looking around online, I think I know what the issue is.

It turns out that Visual Basic checks for overflows on integers, whereas C# does not: https://stackoverflow.com/questions/4515102/unsigned-left-shift-in-vb-net

As a temporary fix, you can remove integer overflow checks in the project properties. Make sure that the "Remove integer overflow checks" is enabled for all configurations and rebuild your solution. Let me know if this works for you or not.

[alt text]<https://camo.githubusercontent.com/ee7729e343d37864d3cd737b93251ef0fefcfcbe/68747470733a2f2f692e696d6775722e636f6d2f546f6e727539792e706e67>

**Comment by ljf118** [comment]
I almost got it. I am just not sure how to turn the output back into an image. Below is my code, would you mind taking a quick look at it and see if you know why the memory stream cannot be truened back into an image.

Thank you Larry

Try
                Dim exq As ExoQuantVB.ExoQuant = New ExoQuantVB.ExoQuant()
                exq.NoTransparency()
                'BMP1 is the dam cat with yellow eyes
                Dim bitmapBytes As Byte() = ConvertToByteArray(bmp1)
                exq.Feed(bitmapBytes)

                exq.QuantizeHq(48) ' "highQuality" is a boolean

                Dim rgba32Palette As Byte() = Nothing
                exq.GetPalette(rgba32Palette, 48)

                Dim indexData As Byte() = Nothing
                Dim numPixels = (bmp.Width * bmp.Height)
                exq.MapImage(numPixels, bitmapBytes, indexData)
                exq.MapImageOrdered(Ww, Hh, bitmapBytes, indexData)

                Dim ms As Stream = New MemoryStream(indexData)
                'The following line gives me an error that the parameter is invalid.
                Dim newImage2 As System.Drawing.Image = System.Drawing.Image.FromStream(ms)

                'PB3 is a generic picturebox
                PB3.Image = newImage2
                PB3.Width = bmp.Width
                PB3.Height = bmp.Height
                Exit Sub
            Catch ex As Exception
                MessageBox.Show("ProcessImage" + ex.Message + " " + ex.Source + ex.StackTrace + " " + ex.Data.ToString)
                Exit Sub
            End Try

________________________________

**Comment by DavidSM64** [comment]
I personally don't use MemoryStream. I find using the Bitmap class to be much easier to work with. 

Here is the test code I use, it loads up a local image `Image.png` and then creates a new image that is reduced to 48 colors called `Image48.png`. You will need to import `System.Runtime.InteropServices` to use the `Marshall.Copy` function.

```vb
' Loads a System.Drawing.Bitmap image from the local file "Image.png"
Dim bmp As Bitmap = New Bitmap("Image.png")

' Copy 32-bit image data into RGBA byte array.
Dim rect As Rectangle = New Rectangle(0, 0, bmp.Width, bmp.Height)
Dim bmpdata As BitmapData = bmp.LockBits(rect, ImageLockMode.[ReadOnly], PixelFormat.Format32bppArgb)
Dim ptr As IntPtr = bmpdata.Scan0
Dim bytes As Integer = bmpdata.Stride * bmp.Height
Dim imgArr As Byte() = New Byte(bytes - 1) {}
Marshal.Copy(ptr, imgArr, 0, bytes)
bmp.UnlockBits(bmpdata)

' Get width and height of image
Dim width As Integer = bmp.Width
Dim height As Integer = bmp.Height

' Number of colors to reduce to
Dim numOfColors As Integer = 48

' Reduce colors using ExoQuant
Console.WriteLine("Reducing colors...")
Dim exq As ExoQuantVB.ExoQuant = New ExoQuantVB.ExoQuant()
exq.Feed(imgArr)
exq.QuantizeHq(numOfColors)
Dim rgba32Palette As Byte() = Nothing
exq.GetPalette(rgba32Palette, numOfColors)
Dim indexData As Byte() = Nothing
exq.MapImageOrdered(width, height, imgArr, indexData)
Console.WriteLine("Finished reducing!")

' Convert `indexData` and `rgba32Palette` to a new RGBA image array.
Dim newImageRGBA As Byte() = New Byte(indexData.Length * 4 - 1) {}
For index As Integer = 0 To indexData.Length - 1
	newImageRGBA(index * 4 + 0) = rgba32Palette(indexData(index) * 4 + 0)
	newImageRGBA(index * 4 + 1) = rgba32Palette(indexData(index) * 4 + 1)
	newImageRGBA(index * 4 + 2) = rgba32Palette(indexData(index) * 4 + 2)
	newImageRGBA(index * 4 + 3) = rgba32Palette(indexData(index) * 4 + 3)
Next

' Convert the new RGBA data into a new bitmap.
Dim newBmp As Bitmap = New Bitmap(width, height, System.Drawing.Imaging.PixelFormat.Format32bppArgb)
Dim bitmapData = newBmp.LockBits(New System.Drawing.Rectangle(0, 0, newBmp.Width, newBmp.Height), System.Drawing.Imaging.ImageLockMode.[WriteOnly], newBmp.PixelFormat)
Marshal.Copy(newImageRGBA, 0, bitmapData.Scan0, newImageRGBA.Length)
newBmp.UnlockBits(bitmapData)

' Note: You can now use `newBmp` as a System.Drawing.Image

' Saves the new bitmap as "Image48.png"
newBmp.Save("Image" & numOfColors & ".png")
Console.WriteLine("Saved as: Image" & numOfColors & ".png")

```

**Comment by ljf118** [comment]
Its working fabulously, even on that Dam cat! Thanks for all your help!

________________________________

**Comment by DavidSM64** [comment]
Glad I could help. :)

I changed the MakeHash() function to include some new safe functions to prevent the overflow/underflow exception from occurring in the first place, so going to the project properties and checking the "Remove integer overflow checks" option shouldn't be necessary anymore hopefully.

```vb
Private Function SafeLShift(ByVal value As UInteger, ByVal amount As UInteger) As UInteger
	Return BitConverter.ToUInt32(BitConverter.GetBytes(value << amount), 0)
End Function

Private Function SafeRShift(ByVal value As UInteger, ByVal amount As UInteger) As UInteger
	Return BitConverter.ToUInt32(BitConverter.GetBytes(value >> amount), 0)
End Function

Private Function SafeMinusForUInteger(ByVal value As UInteger, ByVal amount As UInteger) As UInteger
	If value >= amount Then
		Return value - amount
	Else
		' amount is larger than value, so to prevent arithmetic underflow I need to
		' simulate looping around by subtracting by the max UInteger value.
		Return UInteger.MaxValue - (amount - value)
	End If
End Function

Private Function MakeHash(ByVal rgba As UInteger) As UInteger
	rgba = SafeMinusForUInteger(rgba, SafeRShift(rgba, 13) Or SafeLShift(rgba, 19))
	rgba = SafeMinusForUInteger(rgba, SafeRShift(rgba, 13) Or SafeLShift(rgba, 19))
	rgba = SafeMinusForUInteger(rgba, SafeRShift(rgba, 13) Or SafeLShift(rgba, 19))
	rgba = SafeMinusForUInteger(rgba, SafeRShift(rgba, 13) Or SafeLShift(rgba, 19))
	rgba = SafeMinusForUInteger(rgba, SafeRShift(rgba, 13) Or SafeLShift(rgba, 19))
	rgba = rgba And (EXQ_HASH_SIZE - 1)
	Return rgba
End Function
```
